server:
  port: 2024 #?????
  address: 127.0.0.1
name: xcc
person1:
  name: hello
# ????
person2? {name: world}
arry1:
  - springboot
  - springcloud
# ?????
array2: [vue, react]
msg1: 'hello \n world'    # ?????????
msg2: "Hi \n springboot"  # ?????????
xcc: linux
person:
  name: ${xcc}            # ???????xcc?
  age: 26
  address: [shanghai, huaian]